"$schema" = 'https://starship.rs/config-schema.json'

format = """
[‚ñë‚ñí‚ñì](#a3d2b2)\
[ Óúë ](bg:#a3d2b2 fg:#090c0c)\
[ÓÇ¥](bg:#76f0a0 fg:#a3d2b2)\
$directory\
[ÓÇ¥](fg:#76f0a0 bg:#2a4a35)\
$git_branch\
$git_status\
[ÓÇ¥](fg:#2a4a35 bg:#1d3024)\
$nodejs\
$rust\
$golang\
$php\
[ÓÇ¥](fg:#1d3024 bg:#1a2b1f)\
$time\
[ÓÇ¥ ](fg:#1a2b1f)\
\n$character"""

[directory]
style = "fg:#090c0c bg:#76f0a0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "ÔÄÅ "
"Pictures" = "ÔÄæ "

[git_branch]
symbol = "Ôêò"
style = "bg:#2a4a35"
format = '[[ $symbol $branch ](fg:#76f0a0 bg:#2a4a35)]($style)'

[git_status]
style = "bg:#2a4a35"
format = '[[($all_status$ahead_behind )](fg:#76f0a0 bg:#2a4a35)]($style)'

[nodejs]
symbol = "Óúò"
style = "bg:#1d3024"
format = '[[ $symbol ($version) ](fg:#76f0a0 bg:#1d3024)]($style)'

[rust]
symbol = "Óû®"
style = "bg:#1d3024"
format = '[[ $symbol ($version) ](fg:#76f0a0 bg:#1d3024)]($style)'

[golang]
symbol = "Óòß"
style = "bg:#1d3024"
format = '[[ $symbol ($version) ](fg:#76f0a0 bg:#1d3024)]($style)'

[php]
symbol = "Óòà"
style = "bg:#1d3024"
format = '[[ $symbol ($version) ](fg:#76f0a0 bg:#1d3024)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1a2b1f"
format = '[[ Ôê∫ $time ](fg:#a0cba9 bg:#1a2b1f)]($style)'

[python]
symbol = "üêç "
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "yellow bold"
pyenv_version_name = false
pyenv_prefix = ""
python_binary = ["python3", "python"]
detect_extensions = ["py"]
detect_files = [".python-version", "Pipfile", "__pycache__", "pyproject.toml", "requirements.txt", "setup.py", "tox.ini"]
detect_folders = []